plugins:
  - rubocop-performance

AllCops:
  SuggestExtensions: false
  # 最新のルールを適用する
  NewCops: enable
  # 何のルールに引っかかったか表示する
  DisplayCopNames: true
  # rubocop対象外(リポジトリ毎で調節)
  Exclude:
    - "Gemfile"

### ルールのカスタマイズ

# 日本語にコメントを許可
Style/AsciiComments:
  Enabled: false

# クラス定義のコメントなしを許可
Style/Documentation:
  Enabled: false
